name: Next.js CI

on:
  push:
    branches: [dev]          
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"
  pull_request:
    branches: [dev]          
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: ğŸ§ª Run Vitest
        run: yarn test
        working-directory: ./packages/nextjs
      - name: ğŸ” Run ESLint
        run: yarn lint
        working-directory: ./packages/nextjs

      - name: ğŸ¨ Format Check
        run: yarn format:check
        working-directory: ./packages/nextjs

      - name: ğŸ”¡ Type Check
        run: yarn check-types
        working-directory: ./packages/nextjs

      - name: ğŸ—ï¸ Build App
        run: yarn build
        working-directory: ./packages/nextjs
